[shapeWeight.blend.400]
stroke = 72        # Primary stroke width
contrast = 1.11    # Stroke width contrast
sb = 60            # Primary sidebearings
essx = 1.12        # Proportion of widen of center of "S"
dotsize = 125      # Size of dots
periodsize = 140   # Size of period

jut = 85           # Length of slab serif
refJut = 85        # Reference JUT, used in `m`
vjut = 145         # Length of vertical slab serif
longjut = 175      # Length of long serifs, like that in `i`.

smooth = 195       # Vertical arc size in capital letters.
smallsmooth = 200  # Vertical arc size in lowercase letters.

rbalance = 60
rbalance2 = 15
tbalance = 50
tbalance2 = 30
jbalance = 63
fbalance = 6
onebalance = 30

hook  = 165        # Hook depth in most letters.
ahook = 130
shook = 120
jhook = 135
fhook = 120
hookx = 170
rhook = 110

cthin = 0.75
cthinb = 0.5
vtipfine = 0.8
vtipfineSlab = 0.9


[shapeWeight.blend.100]
stroke = 18
contrast = 1.08
sb = 72
essx = 1.12
dotsize = 53
periodsize = 55

jut = 70
vjut = 145
smooth = 195
rbalance = 60
rbalance2 = 15
cthin = 0.9
cthinb = 0.9
vtipfine = 1
vtipfineSlab = 1


[shapeWeight.blend.200]
cthin = 0.75
cthinb = 0.75
vtipfine = 1
vtipfineSlab = 1

[shapeWeight.blend.300]
cthin = 0.75
cthinb = 0.5
vtipfine = 0.9
vtipfineSlab = 0.9

[shapeWeight.blend.500]
rbalance = 60
rbalance2 = 15

[shapeWeight.blend.600]
# Interpolated

[shapeWeight.blend.700]
# Interpolated

[shapeWeight.blend.800]
# Interpolated

[shapeWeight.blend.900]
stroke = 116
contrast = 1.20
sb = 42
essx = 1.05
dotsize = 180
periodsize = 200

jut = 95
vjut = 200
smooth = 215
rbalance = 50
rbalance2 = 25
