[shapeWidth.blend.500]
width           = 500
[shapeWidth.multiplies.blend.500]
contrast        = 1
stroke          = 1
sb              = 1
jut             = 1
refJut          = 1
longjut         = 1
accentWidth     = 1
rhook           = 1
rbalance        = 1
tbalance        = 1
tbalance2       = 1
archDepth       = 1
smallArchDepth  = 1
essRatio        = 1

# "Grade 9"
[shapeWidth.blend.720]
width           = 720
[shapeWidth.multiplies.blend.720]
contrast        = 1.044
stroke          = 1.103 # Make strokes a little thicker
sb              = 1.891
jut             = 1.323
refJut          = 1.323
longjut         = 1.323
accentWidth     = 1.323
rhook           = 1.323
rbalance        = 1.236
tbalance        = 1.210
tbalance2       = 1.210
archDepth       = 1.103
smallArchDepth  = 1.103
essRatio        = 0.953

# "Grade 8"
[shapeWidth.blend.657]
width           = 657
[shapeWidth.multiplies.blend.657]
stroke          = 1.075 # Make strokes a little thicker
sb              = 1.612
jut             = 1.233
refJut          = 1.233
longjut         = 1.233
accentWidth     = 1.233
rhook           = 1.233
rbalance        = 1.236
tbalance        = 1.154
tbalance2       = 1.154
archDepth       = 1.075
smallArchDepth  = 1.075

# "Grade 7"
[shapeWidth.blend.600]
width           = 600
[shapeWidth.multiplies.blend.600]
stroke          = 1.050 # Make strokes a little thicker
sb              = 1.375
jut             = 1.150
refJut          = 1.150
longjut         = 1.150
accentWidth     = 1.150
rhook           = 1.150
rbalance        = 1.152
tbalance        = 1.100
tbalance2       = 1.100
archDepth       = 1.050
smallArchDepth  = 1.050
essRatio        = 1

# "Grade 6"
[shapeWidth.blend.547]
width           = 547
[shapeWidth.multiplies.blend.547]
stroke          = 1.023 # Make strokes a little thicker
sb              = 1.173
jut             = 1.072
refJut          = 1.072
longjut         = 1.072
accentWidth     = 1.072
rhook           = 1.072
rbalance        = 1.074
tbalance        = 1.049
tbalance2       = 1.049
archDepth       = 1.023
smallArchDepth  = 1.023

# "Grade 4"
[shapeWidth.blend.456]
width           = 456
[shapeWidth.multiplies.blend.456]
contrast        = 1
stroke          = 0.976
sb              = 0.791
jut             = 0.961
refJut          = 0.961
longjut         = 0.961
accentWidth     = 0.961
rhook           = 1
rbalance        = 0.931
tbalance        = 0.953
tbalance2       = 0.953
archDepth       = 0.975
smallArchDepth  = 0.975

# "Grade 3"
[shapeWidth.blend.416]
width           = 416
[shapeWidth.multiplies.blend.416]
contrast        = 1
stroke          = 0.952
sb              = 0.625
jut             = 0.925
refJut          = 0.925
longjut         = 0.925
accentWidth     = 0.925
rhook           = 1
rbalance        = 0.868
tbalance        = 0.909
tbalance2       = 0.909
archDepth       = 0.952
smallArchDepth  = 0.952
essRatio        = 1

# Slab correlation
[shapeWidth-serifs-slab.multiplies.blend.500]
sb = 1.075
