[shapeWeight]
canonicalStrokeWidthMin = 18  # sync with 100 entry below
canonicalStrokeWidthMax = 108 # sync with 900 entry below

[shapeWeight.blend.400]
stroke = 70        # Primary stroke width
contrast = 1.11    # Stroke width contrast
sb = 64            # Primary sidebearings
essRatio = 1.12    # Proportion of widen of center of "S"
dotSize = 125      # Size of dots
periodSize = 140   # Size of period

jut = 85           # Length of slab serif
vjut = 145         # Length of vertical slab serif
longjut = 175      # Length of long serifs, like that in `i`.

archDepth = 195       # Vertical arc size in capital letters.
smallArchDepth = 200  # Vertical arc size in lowercase letters.

rbalance = 60
rbalance2 = 15
tbalance = 45
tbalance2 = 40
jbalance = 63
fbalance = 6
onebalance = 30

hook  = 180 # Hook depth for most letters
ahook = 145 # Hook depth for "a"
shook = 135 # Hook depth for "s"
jhook = 150 # Hook depth for "j"

hookx = 170
rhook = 110 # Hook depth for "r". Not weight-variable.

# Size of attchment tail (X and Y)
tailX = 145
tailY = 142

cthin = 0.75
cthinb = 0.5
vtipfine = 0.8
vtipfineSlab = 0.9


[shapeWeight.blend.100]
stroke = 18
contrast = 1.08
sb = 72
essRatio = 1.12
dotSize = 53
periodSize = 55

jut = 70
vjut = 145
archDepth = 195
rbalance = 60
rbalance2 = 15
cthin = 0.9
cthinb = 0.9
vtipfine = 1
vtipfineSlab = 1

hook  = 165
ahook = 130
shook = 120
jhook = 135

[shapeWeight.blend.200]
vtipfine = 1
vtipfineSlab = 1

[shapeWeight.blend.300]
vtipfine = 0.9
vtipfineSlab = 0.9

[shapeWeight.blend.500]
rbalance = 60
rbalance2 = 15

[shapeWeight.blend.600]
# Interpolated

[shapeWeight.blend.700]
stroke = 96

[shapeWeight.blend.800]
# Interpolated

[shapeWeight.blend.900]
stroke = 114
contrast = 1.20
sb = 56
essRatio = 1.05
dotSize = 180
periodSize = 200

jut = 95
vjut = 200
archDepth = 215
rbalance = 50
rbalance2 = 25
cthin = 0.75
cthinb = 0.5

hook  = 195
ahook = 160
shook = 150
jhook = 165
