[shapeWidth.blend.500]
width        = 500
[shapeWidth.multiplies.blend.500]
stroke       = 1
sb           = 1
jut          = 1
refJut       = 1
longjut      = 1
rhook        = 1
rbalance     = 1
tbalance     = 1
smallsmooth  = 1

# "Grade 9"
[shapeWidth.blend.664]
width        = 664
[shapeWidth.multiplies.blend.664]
stroke       = 1.103 # Make strokes a little thicker
sb           = 1.777
jut          = 1.323
refJut       = 1.323
longjut      = 1.323
rhook        = 1.323
rbalance     = 1.236
tbalance     = 1.210
smallsmooth  = 1.103

# "Grade 8"
[shapeWidth.blend.618]
width        = 618
[shapeWidth.multiplies.blend.618]
stroke       = 1.075 # Make strokes a little thicker
sb           = 1.539
jut          = 1.233
refJut       = 1.233
longjut      = 1.233
rhook        = 1.233
rbalance     = 1.236
tbalance     = 1.154
smallsmooth  = 1.075

# "Grade 7"
[shapeWidth.blend.576]
width        = 576
[shapeWidth.multiplies.blend.576]
stroke       = 1.050 # Make strokes a little thicker
sb           = 1.333
jut          = 1.150
refJut       = 1.150
longjut      = 1.150
rhook        = 1.150
rbalance     = 1.152
tbalance     = 1.100
smallsmooth  = 1.050

# "Grade 6"
[shapeWidth.blend.537]
width        = 537
[shapeWidth.multiplies.blend.537]
stroke       = 1.023 # Make strokes a little thicker
sb           = 1.154
jut          = 1.072
refJut       = 1.072
longjut      = 1.072
rhook        = 1.072
rbalance     = 1.074
tbalance     = 1.049
smallsmooth  = 1.023

# "Grade 4"
[shapeWidth.blend.466]
width        = 466
[shapeWidth.multiplies.blend.466]
stroke       = 0.975
sb           = 0.866
jut          = 0.933
refJut       = 0.933
longjut      = 0.933
rhook        = 1
rbalance     = 0.931
tbalance     = 0.953
smallsmooth  = 0.975

# "Grade 3"
[shapeWidth.blend.434]
width        = 434
[shapeWidth.multiplies.blend.434]
stroke       = 0.952
sb           = 0.750
jut          = 0.870
refJut       = 0.870
longjut      = 0.870
rhook        = 1
rbalance     = 0.868
tbalance     = 0.909
smallsmooth  = 0.952
