[shapeWidth.multiplies.blend.500]
width        = 1
stroke       = 1
sb           = 1
jut          = 1
longjut      = 1
rhook        = 1
rbalance     = 1
tbalance     = 1
smallsmooth  = 1

[shapeWidth.multiplies.blend.664]
width        = 1.328 # 664 for normal char
stroke       = 1.103 # Make strokes a little thicker
sb           = 1.777
jut          = 1.323
longjut      = 1.323
rhook        = 1.323
rbalance     = 1.236
tbalance     = 1.210
smallsmooth  = 1.103

[shapeWidth.multiplies.blend.618]
width        = 1.236 # 618 for normal char
stroke       = 1.075 # Make strokes a little thicker
sb           = 1.539
jut          = 1.233
longjut      = 1.233
rhook        = 1.233
rbalance     = 1.236
tbalance     = 1.154
smallsmooth  = 1.075

[shapeWidth.multiplies.blend.576]
width        = 1.152 # 576mem for normal char
stroke       = 1.050 # Make strokes a little thicker
sb           = 1.333
jut          = 1.150
longjut      = 1.150
rhook        = 1.150
rbalance     = 1.152
tbalance     = 1.100
smallsmooth  = 1.050

[shapeWidth.multiplies.blend.537]
width        = 1.074 # 537mem for normal char
stroke       = 1.023 # Make strokes a little thicker
sb           = 1.154
jut          = 1.072
longjut      = 1.072
rhook        = 1.072
rbalance     = 1.074
tbalance     = 1.049
smallsmooth  = 1.023

[shapeWidth.multiplies.blend.466]
width        = 0.932 # 466mem for normal char
stroke       = 0.975
sb           = 0.866
jut          = 0.933
longjut      = 0.933
rhook        = 1
rbalance     = 0.931
tbalance     = 0.953
smallsmooth  = 0.975

[shapeWidth.multiplies.blend.434]
width        = 0.868 # 434mem for normal char
stroke       = 0.952
sb           = 0.750
jut          = 0.870
longjut      = 0.870
rhook        = 1
rbalance     = 0.868
tbalance     = 0.909
smallsmooth  = 0.952
