# Building plans
# Sans
[buildPlans.iosevka]
family = "Iosevka"

[buildPlans.iosevka-term]
family = "Iosevka Term"
design = ["term"]

[buildPlans.iosevka-type]
family = "Iosevka Type"
design = ["type"]

[buildPlans.iosevka-cc]
family = "IosevkaCC"
design = ["cc"]

# Slab
[buildPlans.iosevka-slab]
family = "Iosevka Slab"
design = ["slab"]

[buildPlans.iosevka-term-slab]
family = "Iosevka Term Slab"
design = ["term", "slab"]

[buildPlans.iosevka-type-slab]
family = "Iosevka Type Slab"
design = ["type", "slab"]

[buildPlans.iosevka-cc-slab]
family = "IosevkaCC Slab"
design = ["cc", "slab"]

# SSxx
[buildPlans.iosevka-ss01]
family = "Iosevka SS01"
design = ["ss01"]

[buildPlans.iosevka-term-ss01]
family = "Iosevka Term SS01"
design = ["term", "ss01"]

[buildPlans.iosevka-ss02]
family = "Iosevka SS02"
design = ["ss02"]

[buildPlans.iosevka-term-ss02]
family = "Iosevka Term SS02"
design = ["term", "ss02"]

[buildPlans.iosevka-ss03]
family = "Iosevka SS03"
design = ["ss03"]

[buildPlans.iosevka-term-ss03]
family = "Iosevka Term SS03"
design = ["term", "ss03"]

[buildPlans.iosevka-ss04]
family = "Iosevka SS04"
design = ["ss04"]

[buildPlans.iosevka-term-ss04]
family = "Iosevka Term SS04"
design = ["term", "ss04"]

[buildPlans.iosevka-ss05]
family = "Iosevka SS05"
design = ["ss05"]

[buildPlans.iosevka-term-ss05]
family = "Iosevka Term SS05"
design = ["term", "ss05"]

[buildPlans.iosevka-ss06]
family = "Iosevka SS06"
design = ["ss06"]

[buildPlans.iosevka-term-ss06]
family = "Iosevka Term SS06"
design = ["term", "ss06"]

[buildPlans.iosevka-ss07]
family = "Iosevka SS07"
design = ["ss07"]

[buildPlans.iosevka-term-ss07]
family = "Iosevka Term SS07"
design = ["term", "ss07"]

[buildPlans.iosevka-ss08]
family = "Iosevka SS08"
design = ["ss08"]

[buildPlans.iosevka-term-ss08]
family = "Iosevka Term SS08"
design = ["term", "ss08"]

[buildPlans.iosevka-ss09]
family = "Iosevka SS09"
design = ["ss09"]

[buildPlans.iosevka-term-ss09]
family = "Iosevka Term SS09"
design = ["term", "ss09"]

[buildPlans.iosevka-ss10]
family = "Iosevka SS10"
design = ["ss10"]

[buildPlans.iosevka-term-ss10]
family = "Iosevka Term SS10"
design = ["term", "ss10"]

[buildPlans.iosevka-ss11]
family = "Iosevka SS11"
design = ["ss11"]

[buildPlans.iosevka-term-ss11]
family = "Iosevka Term SS11"
design = ["term", "ss11"]


# Export plans
# This mapping affects the process of creating ZIP archives only
[exportPlans]
01-iosevka = "iosevka"
02-iosevka-term = "iosevka-term"
03-iosevka-type = "iosevka-type"
04-iosevka-cc = "iosevka-cc"
05-iosevka-slab = "iosevka-slab"
06-iosevka-term-slab = "iosevka-term-slab"
07-iosevka-type-slab = "iosevka-type-slab"
08-iosevka-cc-slab = "iosevka-cc-slab"
iosevka-ss01 = "iosevka-ss01"
iosevka-term-ss01 = "iosevka-term-ss01"
iosevka-ss02 = "iosevka-ss02"
iosevka-term-ss02 = "iosevka-term-ss02"
iosevka-ss03 = "iosevka-ss03"
iosevka-term-ss03 = "iosevka-term-ss03"
iosevka-ss04 = "iosevka-ss04"
iosevka-term-ss04 = "iosevka-term-ss04"
iosevka-ss05 = "iosevka-ss05"
iosevka-term-ss05 = "iosevka-term-ss05"
iosevka-ss06 = "iosevka-ss06"
iosevka-term-ss06 = "iosevka-term-ss06"
iosevka-ss07 = "iosevka-ss07"
iosevka-term-ss07 = "iosevka-term-ss07"
iosevka-ss08 = "iosevka-ss08"
iosevka-term-ss08 = "iosevka-term-ss08"
iosevka-ss09 = "iosevka-ss09"
iosevka-term-ss09 = "iosevka-term-ss09"
iosevka-ss10 = "iosevka-ss10"
iosevka-term-ss10 = "iosevka-term-ss10"
iosevka-ss11 = "iosevka-ss11"
iosevka-term-ss11 = "iosevka-term-ss11"

# TTC collection plans
[collectPlans.iosevka]
from = [
	"iosevka",
	"iosevka-term",
	"iosevka-type",
	"iosevka-cc"
]

[collectPlans.iosevka-slab]
from = [
	"iosevka-slab",
	"iosevka-term-slab",
	"iosevka-type-slab",
	"iosevka-cc-slab"
]

# Weight mappings (style => CSS)
# Comment the lines to build less weights
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `parameters.toml` instead.
[weights]
thin = 100
extralight = 200
light = 300
book = 400
medium = 500
semibold = 600
bold = 700
extrabold = 800
heavy = 900

# Slant mappings (style => CSS)
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `parameters.toml` instead.
[slants]
upright = "normal"
italic = "italic"
oblique = "oblique"


################################################
# To define your custom build                  #
# Add a new term into buildPlans               #
# and run `npm run build -- fonts:<plan name>` #
################################################
# [buildPlans.iosevka-custom]            # <iosevka-custom> is your plan name
# family = "Iosevka Custom"              # Font menu family name
# design = ["common styles"]             # Common styles
# upright = ["upright-only", "styles"]   # Upright-only styles
# italic = ["italic-only", "styles"]     # Italic-only styles
# oblique = ["oblique-only", "styles"]   # Oblique-only styles
