version = 1
entrySelector = 3

glyf = []

[head]
checkSumAdjustment = 369537602
created = "2014-12-06T22:05:19.000Z"
flags = 11
fontDirectionHint = 2
fontRevision = 1
glyphDataFormat = 0
indexToLocFormat = 0
lowestRecPPEM = 8
macStyle = 0
magickNumber = 1594834165
modified = "2014-12-06T22:20:03.000Z"
unitsPerEm = 1000
version = 1
xMax = 306
xMin = 34
yMax = 682
yMin = 0

[hhea]
advanceWidthMax = 374
ascent = 812
caretOffset = 0
caretSlopeRise = 1
caretSlopeRun = 0
descent = -212
lineGap = 92
metricDataFormat = 0
minLeftSideBearing = 34
minRightSideBearing = 68
numOfLongHorMetrics = 1
reserved0 = 0
reserved1 = 0
reserved2 = 0
reserved3 = 0
version = 1
xMaxExtent = 306

["OS/2"]
achVendID = "PfEd"
bArmStyle = 0
bContrast = 0
bFamilyType = 2
bLetterform = 0
bMidline = 0
bProportion = 3
bSerifStyle = 0
bStrokeVariation = 0
bWeight = 6
bXHeight = 0
fsSelection = 192
fsType = 0
sCapHeight = 0
sFamilyClass = 0
sTypoAscender = 812
sTypoDescender = -212
sTypoLineGap = 92
sxHeight = 792
ulCodePageRange1 = 1
ulCodePageRange2 = 0
ulUnicodeRange1 = 1
ulUnicodeRange2 = 268435456
ulUnicodeRange3 = 0
ulUnicodeRange4 = 0
usBreakChar = 32
usDefaultChar = 0
usFirstCharIndex = 0
usLastCharIndex = 0
usMaxContext = 1
usWeightClass = 400
usWidthClass = 5
usWinAscent = 812
usWinDescent = 212
version = 4
xAvgCharWidth = 1031
yStrikeoutPosition = 265
yStrikeoutSize = 51
ySubscriptXOffset = 0
ySubscriptXSize = 665
ySubscriptYOffset = 143
ySubscriptYSize = 716
ySuperscriptXOffset = 0
ySuperscriptXSize = 665
ySuperscriptYOffset = 491
ySuperscriptYSize = 716

[name]
fontFamily = "node-sfnt"
fontSubFamily = "regular"
fullName = "node-sfnt"
postScriptName = "node-sfnt"
uniqueSubFamily = "node-sfnt blank font"
version = "Version 1.0"

[post]
format = 2
isFixedPitch = 0
italicAngle = 0
maxMemType1 = 1
maxMemType42 = 0
minMemType1 = 0
minMemType42 = 0
postoints = 65411
underlinePosition = 50
underlineThickness = 0