[simple.calt-center-ops]
ligGroup =  'center-ops'
desc = 'Vertically align some of the operators (like `*`) to the center position it is before or after a "center" operator (like `+`)'

[simple.calt-arrow]
ligGroup =  "arrow"
desc = 'Enable ligation set that forms arrows'

[simple.calt-arrow2]
ligGroup =  "arrow2"
desc = 'Enable ligation for more arrows, like `>>=`'

[simple.calt-trig]
ligGroup =  "trig"
desc = 'Enable ligation for `<|`, `|>` , `<||`, and other bar-and-angle-bracket symbols'

[simple.calt-eqeqeq]
ligGroup =  "eqeqeq"
desc = 'Enable special triple-line ligation for `===` only'

[simple.calt-eqeq]
ligGroup =  "eqeq"
desc = 'Enable ligation for `==` and `===`'

[simple.calt-ineq]
ligGroup =  "ineq"
desc = 'Enable ligation for `<=` and `>=`'

[simple.calt-exeqeq]
ligGroup =  "exeqeq"
desc = 'Enable special triple-line ligation for `!==` only'

[simple.calt-eqexeq]
ligGroup =  "eqexeq"
desc = 'Enable special triple-line ligation for `=!=` only'

[simple.calt-exeq]
ligGroup =  "exeq"
desc = 'Enable ligation for `!=` and `!==`'

[simple.calt-tildeeq]
ligGroup =  "tildeeq"
desc = 'Enable ligation for `~=` as inequality'

[simple.calt-eqslasheq]
ligGroup = "eqslasheq"
desc = 'Enable special triple-line ligation for `=/=` as inequality'

[simple.calt-slasheq]
ligGroup = "slasheq"
desc = 'Enable ligation for `/=` and `=/=` as inequality'

[simple.calt-ltgt-ne]
ligGroup = "ltgt-ne"
desc = 'Enable ligation for `<>` as inequality'

[simple.calt-ltgt-diamond]
ligGroup = "ltgt-diamond"
desc = 'Enable ligation for `<>` as diamond'

[simple.calt-brst]
ligGroup = "brst"
desc = 'Center asterisk in `(*` and `*)`'

[simple.calt-plusplus]
ligGroup =  "plusplus"
desc = 'Enable ligation for `++` and further plus-chaining'

[simple.calt-kern-dotty]
ligGroup =  "kern-dotty"
desc = 'Move connecting dotty punctuations closer, like for `::`, `:::` and `...`.'

[simple.calt-logic]
ligGroup =  "logic"
desc = 'Enable ligation for `/\` and `\/`'

[simple.calt-llgg]
ligGroup =  "llgg"
desc = 'Enable ligation for `<<`, `>>` and other angle-bracket chaining'

[simple.calt-dotoper]
ligGroup =  "dotoper"
desc = 'Treat dot (`.`) as operator and perform chained centering'

[simple.calt-arrowZALE]
ligGroup =  "arrowZALE"
desc = 'Treat `<=` as arrow'

[simple.calt-arrowZAGE]
ligGroup =  "arrowZAGE"
desc = 'Treat `>=` as co-arrow'

[simple.calt-html-comment]
ligGroup =  "html-comment"
desc = 'Enable ligation for `<!--` and `<!---`'

[composite.ligset-calt]
disableHives = true
tag     = 'calt'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'eqeq', 'ineq', 'exeq',  'plusplus', 'kern-dotty']
brief   = 'Default'
desc    = 'Default setting in text editors'

[composite.ligset-dlig]
tag     = 'dlig'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'arrow2', 'llgg', 'eqeq', 'ineq', 'exeq', 'ltgt-diamond', 'plusplus', 'kern-dotty', 'dotoper', 'logic', 'brst']
brief   = 'Discretionary'
desc    = 'Discretionary ligatures'

[composite.ligset-javascript]
tag     = 'JSPT'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'eqeqeq', 'eqeq', 'ineq', 'exeqeq', 'exeq', 'plusplus', 'kern-dotty']
desc    = 'JavaScript'

[composite.ligset-php]
tag     = 'PHPX'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'eqeqeq', 'eqeq', 'ineq', 'exeqeq', 'exeq', 'plusplus', 'kern-dotty']
desc    = 'PHP'

[composite.ligset-ml]
tag     = 'MLXX'
buildup = ['center-ops', 'arrow', 'trig', 'eqeq', 'ineq', 'ltgt-ne', 'brst', 'plusplus', 'logic']
desc    = 'ML'

[composite.ligset-fsharp]
tag     = 'FSHP'
buildup = ['center-ops', 'arrow', 'trig', 'eqeq', 'ineq', 'ltgt-ne', 'brst', 'plusplus', 'logic']
desc    = 'F#'

[composite.ligset-fstar]
tag     = 'FSTA'
buildup = ['center-ops', 'arrow', 'trig', 'eqeqeq', 'ineq', 'eqexeq', 'brst', 'plusplus', 'logic']
desc    = 'F*'

[composite.ligset-haskell]
tag     = 'HSKL'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'slasheq', 'ltgt-diamond', 'plusplus', 'dotoper', 'kern-dotty', 'logic']
desc    = 'Haskell'

[composite.ligset-idris]
tag     = 'IDRS'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'slasheq', 'ltgt-diamond', 'plusplus', 'dotoper', 'kern-dotty', 'logic']
desc    = 'Idris'

[composite.ligset-elm]
tag     = 'ELMX'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'slasheq', 'ltgt-diamond', 'plusplus', 'dotoper', 'kern-dotty', 'logic']
desc    = 'Elm'

[composite.ligset-purescript]
tag     = 'PURS'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'slasheq', 'ltgt-diamond', 'plusplus', 'dotoper', 'kern-dotty', 'logic']
desc    = 'PureScript'

[composite.ligset-patel]
tag     = 'PTLX'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'exeq', 'ltgt-diamond', 'plusplus']
desc    = 'PatEL'

[composite.ligset-swift]
tag     = 'SWFT'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'exeq', 'ltgt-diamond', 'plusplus']
desc    = 'Swift'

[composite.ligset-coq]
tag     = 'COQX'
buildup = ['center-ops', 'arrow', 'arrow2', 'trig', 'llgg', 'eqeq', 'ineq', 'ltgt-ne', 'plusplus', 'dotoper', 'logic', 'brst']
desc    = 'Coq'

[composite.ligset-matlab]
tag     = 'MTLB'
buildup = ['center-ops', 'arrow', 'html-comment', 'trig', 'llgg', 'eqeq', 'ineq', 'tildeeq', 'plusplus', 'kern-dotty']
desc    = 'Matlab'
