[iosevka]
family = 'Iosevka'
version = '1.4.1'
codename = 'Aureta'
copyright = 'Copyright (c) 2015 Belleve Invis.'
licence = '''This font software is licenced under the SIL Open Font Licence, Version 1.1. This is licence is avaliable with a FAQ at: http://scripts.sil.org/OFL. This font software is distributes on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence fot the specific language, premissions and limitations governing your use of this font software.'''

leading = 1250     # Leading
linegap = 0        # Additional line gap
width = 500        # Character width. Increase this if you think that Iosevka is too narrow
cap = 735          # Cap height (as well as ascender)
xheight = 530      # X-height
#descender = -205  # Unnecessary

contrast = 1.11111 # Stroke width contrast
essx = 1.12        # Contrast of the middle of 'S'

italicangle = 0    # Slant angle, in degrees

accent = 155       # Height of accent marks
accentx = 200      # Wideness of accent marks
overshoot = -8     # Vertical overshoot for arcs
overshootx = -8    # Horizontal overshoot for arcs
oxhook = -5        # Horizontal overshoot for hook tips
fovershoot = -40   # Overshoot of the top end of italic `f`

longjut = 175      # Length of long serifs, like that in `i`
jut = 85           # Length of short serifs, used in Slab only
vjut = 145         # Length of vertical serifs, used in Slab only

superness = 2.2    # Superness of arcs

barpos = 0.52      # Position of the middle bar in most letters, like `E`
overlaypos = 0.52  # Position of the overlay mark
ebarpos = 0.50     # Position of the middle bar in `e`
gbarpos = 0.42
pbarpos = 0.53
fivebarpos = 0.63

hook  = 155        # Hook depth in most letters
ahook = 130
shook = 110
jhook = 135
fhook = 120
rhook = 90
hookx = 170

smooth = 195
smallsmooth = 220
smoothadjust = 120

tbalance = 50
tbalance2 = 30
rbalance = 60
rbalance2 = 15
jbalance = 63
fbalance = 6
onebalance = 30

isBold = false
isItalic = false

lllcrowdedness = 3.33333333

[iosevka.variantSelector]

# Spacings
[cjk]
cjk = true

[cc]
cjk = true
cjkSpacing = true

[cc.adds]
family = 'CC'

# Weights
[w-thin]
weight = 100
style = 'Thin'

stroke = 18
sb = 72
dotsize = 50
periodsize = 55

cthin = 0.9
cthinb = 0.9
vtipfine = 1
shoulderfine = 0.8

[w-extralight]
weight = 200
style = 'Extralight'

stroke = 36
sb = 68
dotsize = 70
periodsize = 77

cthin = 0.75
cthinb = 0.75
vtipfine = 1

[w-light]
weight = 300
style = 'Light'

stroke = 56
sb = 64
dotsize = 100
periodsize = 115

vtipfine = 0.9

[w-book]
isBold = false
weight = 400
style = ''

sb = 60
stroke = 72
dotsize = 125
periodsize = 140

[w-medium]
weith = 500
style = 'Medium'

sb = 54
stroke = 88
dotsize = 140
periodsize = 145
essx = 1.07

rbalance = 55
rbalance2 = 20
smooth = 203

[w-bold]
isBold = true
weight = 700
style = 'Bold'

sb = 45
stroke = 111
dotsize = 160
periodsize = 180
essx = 1.05
essxq = 1.15
jut = 90
vjut = 165

barpos = 0.51
fivebarpos = 0.64
rbalance = 50
rbalance2 = 25
rhook = 95
smooth = 210

[w-heavy]
isBold = true
weight = 900
style = 'Heavy'

sb = 42
stroke = 126
dotsize = 180
periodsize = 200
essx = 1.03
essxq = 1.15
jut = 100
vjut = 175

barpos = 0.51
fivebarpos = 0.64
rbalance = 50
rbalance2 = 25
rhook = 105
smooth = 215

# Slants
[s-upright]
isItalic = false

[s-italic]
isItalic = true
italicangle = 10
jhook = 120

[s-italic.adds]
style = " Italic"

# Slab variant
[slab]
slab = true
onebalance = 10
overshootx = -16
[slab.multiplies]
sb = 1.1
[slab.adds]
family = " Slab"

# Variants
[v-l-hooky.variantSelector]
l = 'hooky'
[v-i-hooky.variantSelector]
dotlessi = 'hooky'
[v-l-zshaped.variantSelector]
l = 'zshaped'
[v-i-zshaped.variantSelector]
dotlessi = 'zshaped'
[v-l-serifed.variantSelector]
l = 'serifed'
[v-i-serifed.variantSelector]
dotlessi = 'serifed'
[v-l-italic.variantSelector]
l = 'italic'
[v-i-italic.variantSelector]
dotlessi = 'italic'