[iosevka]
family = 'Iosevka'
version = '1.10.0'
codename = 'Juno'
copyright = 'Copyright (c) 2015-2016 Belleve Invis.'
licence = '''This font software is licenced under the SIL Open Font Licence, Version 1.1. This is licence is avaliable with a FAQ at: http://scripts.sil.org/OFL. This font software is distributes on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence fot the specific language, premissions and limitations governing your use of this font software.'''
manufacturer = 'Belleve Invis'
designer = 'Belleve Invis'
description = 'Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka'

leading = 1250     # Default line height times 1000.
descenderPad = 0   # Additional line height, added to descender.
width = 500        # Character width. Increase this if you think that Iosevka is too narrow.
cap = 735          # Cap height (as well as ascender).
xheight = 530      # X-height.
#descender = -205  # Depth of descender. Currently unused.

ideoMid  = 365
parenMid = 365

contrast = 1.11111 # Stroke width contrast.
essx = 1.12        # Contrast of the middle of 'S'.

slantAngle = 0     # Slant angle, in degrees.

accent = 155       # Height of accent marks.
accentx = 200      # Width of accent marks.
overshoot = -8     # Vertical overshoot for arcs.
overshootx = -8    # Horizontal overshoot for arcs.
oxhook = -5        # Horizontal overshoot for hook tips.
fovershoot = -40   # Overshoot of the top end of italic `f`.

longjut = 175      # Length of long serifs, like that in `i`.
jut = 85           # Length of short serifs, used in Slab only.
vjut = 145         # Length of vertical serifs, used in Slab only.

smooth = 195       # Vertical arc size in capital letters.
smallsmooth = 220  # Vertical arc size in lowercase letters.
smoothadjust = 120 # Parameter to balance arcs in slanted shapes.
superness = 2.2    # Superness of arcs.

barpos = 0.525     # Position of the middle bar in most letters, like `E`.
overlaypos = 0.52  # Position of the overlay mark.
ebarpos = 0.50     # Position of the middle bar in `e`.
gbarpos = 0.42
pbarpos = 0.53
fivebarpos = 0.64

hook  = 155        # Hook depth in most letters.
ahook = 130
shook = 110
jhook = 135
fhook = 120
rhook = 90
hookx = 170

tbalance = 50
tbalance2 = 30
rbalance = 60
rbalance2 = 15
jbalance = 63
fbalance = 6
onebalance = 30

isBold = false     # Mark the font as bold?
isItalic = false   # Use italic shapes?

lllcrowdedness = 3.33333333

spacing = 1 # Spacing indicator

# Powerline-specific parameters
powerlineScaleY = 1 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 0 # Vertical shift
powerlineShiftX = 0 # Horizontal shift

[iosevka.variantSelector]

[iosevka.sscompose.upright]
ss01 = ['cv01', 'cv11', 'cv05', 'cv10', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32'] # Andale Mono Style
ss02 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv13', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32'] # Anonymous Pro Style
ss03 = ['cv01', 'cv11', 'cv03', 'cv07', 'cv13', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32'] # Consolas Style
ss04 = ['cv01', 'cv12', 'cv03', 'cv08', 'cv13', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31'] # Menlo Style
ss05 = ['cv01', 'cv24', 'cv03', 'cv08', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv33'] # Fira Mono Style
ss06 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv14', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32'] # Liberation Mono Style
ss07 = ['cv02', 'cv12', 'cv06', 'cv10', 'cv13', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32'] # Monaco Style
ss08 = ['cv01', 'cv11', 'cv03', 'cv07', 'cv14', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31'] # Pragmata Pro Style
ss09 = ['cv01', 'cv11', 'cv05', 'cv08', 'cv14', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv31'] # Source Code Pro Style

[iosevka.sscompose.italic]
ss01 = ['cv01', 'cv11', 'cv05', 'cv10', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32'] # Andale Mono Style
ss02 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv13', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32'] # Anonymous Pro Style
ss03 = ['cv02', 'cv12', 'cv04', 'cv08', 'cv13', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32'] # Consolas Style
ss04 = ['cv01', 'cv12', 'cv03', 'cv08', 'cv13', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31'] # Menlo Style
ss05 = ['cv01', 'cv24', 'cv03', 'cv08', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv33'] # Fira Mono Style
ss06 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv14', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32'] # Liberation Mono Style
ss07 = ['cv02', 'cv12', 'cv06', 'cv10', 'cv13', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32'] # Monaco Style
ss08 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv14', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31'] # Pragmata Pro Style
ss09 = ['cv02', 'cv12', 'cv04', 'cv08', 'cv14', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv31'] # Source Code Pro Style

[verbose]
verbose = true

# Spacings

[term]
spacing = 0
disableLigation = true

[term.adds]
family = ' Term'

[cc]
spacing = 3
fullwidth_codes = [
	164, #¤
	167, #§
	177, #±
	183, #·
	215, #×
	247, #÷
	711, #ˇ
	713, #ˉ
	8212, #—
	8214, #‖
	8216, #‘
	8217, #’
	8220, #“
	8221, #”
	8230, #…
	8242, #′
	8243, #″
	8251, #※
	8451, #℃
	8544, #Ⅰ
	8545, #Ⅱ
	8546, #Ⅲ
	8547, #Ⅳ
	8548, #Ⅴ
	8549, #Ⅵ
	8550, #Ⅶ
	8551, #Ⅷ
	8552, #Ⅸ
	8553, #Ⅹ
	8554, #Ⅺ
	8555, #Ⅻ
	8592, #←
	8593, #↑
	8594, #→
	8595, #↓
	8712, #∈
	8719, #∏
	8721, #∑
	8733, #∝
	8734, #∞
	8736, #∠
	8741, #∥
	8743, #∧
	8744, #∨
	8745, #∩
	8746, #∪
	8747, #∫
	8750, #∮
	8756, #∴
	8757, #∵
	8758, #∶
	8759, #∷
	8765, #∽
	8776, #≈
	8780, #≌
	8800, #≠
	8801, #≡
	8804, #≤
	8805, #≥
	8814, #≮
	8815, #≯
	8857, #⊙
	8869, #⊥
	8978, #⌒
	9312, #①
	9313, #②
	9314, #③
	9315, #④
	9316, #⑤
	9317, #⑥
	9318, #⑦
	9319, #⑧
	9320, #⑨
	9321, #⑩
	9332, #⑴
	9333, #⑵
	9334, #⑶
	9335, #⑷
	9336, #⑸
	9337, #⑹
	9338, #⑺
	9339, #⑻
	9340, #⑼
	9341, #⑽
	9342, #⑾
	9343, #⑿
	9344, #⒀
	9345, #⒁
	9346, #⒂
	9347, #⒃
	9348, #⒄
	9349, #⒅
	9350, #⒆
	9351, #⒇
	9352, #⒈
	9353, #⒉
	9354, #⒊
	9355, #⒋
	9356, #⒌
	9357, #⒍
	9358, #⒎
	9359, #⒏
	9360, #⒐
	9361, #⒑
	9362, #⒒
	9363, #⒓
	9364, #⒔
	9365, #⒕
	9366, #⒖
	9367, #⒗
	9368, #⒘
	9369, #⒙
	9370, #⒚
	9371, #⒛
	9472, #─
	9473, #━
	9474, #│
	9475, #┃
	9476, #┄
	9477, #┅
	9478, #┆
	9479, #┇
	9480, #┈
	9481, #┉
	9482, #┊
	9483, #┋
	9484, #┌
	9485, #┍
	9486, #┎
	9487, #┏
	9488, #┐
	9489, #┑
	9490, #┒
	9491, #┓
	9492, #└
	9493, #┕
	9494, #┖
	9495, #┗
	9496, #┘
	9497, #┙
	9498, #┚
	9499, #┛
	9500, #├
	9501, #┝
	9502, #┞
	9503, #┟
	9504, #┠
	9505, #┡
	9506, #┢
	9507, #┣
	9508, #┤
	9509, #┥
	9510, #┦
	9511, #┧
	9512, #┨
	9513, #┩
	9514, #┪
	9515, #┫
	9516, #┬
	9517, #┭
	9518, #┮
	9519, #┯
	9520, #┰
	9521, #┱
	9522, #┲
	9523, #┳
	9524, #┴
	9525, #┵
	9526, #┶
	9527, #┷
	9528, #┸
	9529, #┹
	9530, #┺
	9531, #┻
	9532, #┼
	9533, #┽
	9534, #┾
	9535, #┿
	9536, #╀
	9537, #╁
	9538, #╂
	9539, #╃
	9540, #╄
	9541, #╅
	9542, #╆
	9543, #╇
	9544, #╈
	9545, #╉
	9546, #╊
	9547, #╋
	9632, #■
	9633, #□
	9650, #▲
	9651, #△
	9670, #◆
	9671, #◇
	9675, #○
	9678, #◎
	9679, #●
	9733, #★
	9734, #☆
	9792, #♀
	9794, #♂
	8211, #–
	8213, #―
	8229, #‥
	8245, #‵
	8453, #℅
	8457, #℉
	8598, #↖
	8599, #↗
	8600, #↘
	8601, #↙
	8725, #∕
	8735, #∟
	8739, #∣
	8786, #≒
	8806, #≦
	8807, #≧
	8895, #⊿
	9552, #═
	9553, #║
	9554, #╒
	9555, #╓
	9556, #╔
	9557, #╕
	9558, #╖
	9559, #╗
	9560, #╘
	9561, #╙
	9562, #╚
	9563, #╛
	9564, #╜
	9565, #╝
	9566, #╞
	9567, #╟
	9568, #╠
	9569, #╡
	9570, #╢
	9571, #╣
	9572, #╤
	9573, #╥
	9574, #╦
	9575, #╧
	9576, #╨
	9577, #╩
	9578, #╪
	9579, #╫
	9580, #╬
	9581, #╭
	9582, #╮
	9583, #╯
	9584, #╰
	9585, #╱
	9586, #╲
	9587, #╳
	9601, #▁
	9602, #▂
	9603, #▃
	9604, #▄
	9605, #▅
	9606, #▆
	9607, #▇
	9608, #█
	9609, #▉
	9610, #▊
	9611, #▋
	9612, #▌
	9613, #▍
	9614, #▎
	9615, #▏
	9619, #▓
	9620, #▔
	9621, #▕
	9660, #▼
	9661, #▽
	9698, #◢
	9699, #◣
	9700, #◤
	9701, #◥
	9737, #☉
	8853, #⊕
]

[cc.adds]
family = 'CC'



# Weights

[w-book]
isBold = false
weight = 400       # "Weight" metadata.
style = ''

sb = 60            # Side bearing.
stroke = 72        # Stroke width of horizontal strokes.
dotsize = 125      # "Visual" size of dots in /i.
periodsize = 140   # "Visual" size of period.

[w-thin]
weight = 100
style = 'Thin'

stroke = 18
sb = 72
dotsize = 53
periodsize = 55

cthin = 0.9
cthinb = 0.9
vtipfine = 1
shoulderfine = 0.8
pbarpos = 0.5

[w-extralight]
weight = 200
style = 'Extralight'

stroke = 36
sb = 68
dotsize = 70
periodsize = 77

cthin = 0.75
cthinb = 0.75
vtipfine = 1
pbarpos = 0.5

[w-light]
weight = 300
style = 'Light'

stroke = 56
sb = 64
dotsize = 100
periodsize = 115

vtipfine = 0.9
pbarpos = 0.51

[w-medium]
weight = 500
style = 'Medium'

sb = 54
stroke = 90
dotsize = 140
periodsize = 165
essx = 1.07

rbalance = 55
rbalance2 = 20
smooth = 203

[w-bold]
isBold = true
weight = 700
style = 'Bold'

sb = 45
stroke = 108
dotsize = 160
periodsize = 180
essx = 1.05
essxq = 1.15
jut = 90
vjut = 165

barpos = 0.51
fivebarpos = 0.64
rbalance = 50
rbalance2 = 25
rhook = 95
smooth = 210

[w-heavy]
isBold = true
weight = 900
style = 'Heavy'

sb = 42
stroke = 126
dotsize = 180
periodsize = 200
essx = 1.03
essxq = 1.15
jut = 100
vjut = 175

barpos = 0.51
fivebarpos = 0.64
rbalance = 50
rbalance2 = 25
rhook = 105
smooth = 215

# Slants
[s-upright]
isItalic = false

[s-italic]
isItalic = true
slantAngle = 10
jhook = 120

[s-italic.adds]
style = " Italic"

[s-oblique]
isOblique = true
isItalic = false
slantAngle = 10
jhook = 120

[s-oblique.adds]
style = " Oblique"

# Slab variant
[slab]
slab = true
onebalance = 10
overshootx = -16
[slab.multiplies]
sb = 1.1
[slab.adds]
family = " Slab"

# Variants
[v-l-hooky.variantSelector]
l = 'hooky'
[cv09.variantSelector]
l = 'hooky'

[v-i-hooky.variantSelector]
dotlessi = 'hooky'
[cv05.variantSelector]
dotlessi = 'hooky'

[v-l-zshaped.variantSelector]
l = 'zshaped'
[cv10.variantSelector]
l = 'zshaped'

[v-i-zshaped.variantSelector]
dotlessi = 'zshaped'
[cv06.variantSelector]
dotlessi = 'zshaped'

[v-l-serifed.variantSelector]
l = 'serifed'
[cv07.variantSelector]
l = 'serifed'

[v-i-serifed.variantSelector]
dotlessi = 'serifed'
[cv03.variantSelector]
dotlessi = 'serifed'

[v-l-italic.variantSelector]
l = 'italic'
[cv08.variantSelector]
l = 'italic'

[v-i-italic.variantSelector]
dotlessi = 'italic'
[cv04.variantSelector]
dotlessi = 'italic'

[v-l-tailed.variantSelector]
l = 'tailed'
[cv27.variantSelector]
l = 'tailed'

[v-l-hookybottom.variantSelector]
l = 'hookybottom'
[cv28.variantSelector]
l = 'hookybottom'

[v-a-singlestorey.variantSelector]
a = 'singlestorey'
[cv02.variantSelector]
a = 'singlestorey'

[v-a-doublestorey.variantSelector]
a = 'doublestorey'
[cv01.variantSelector]
a = 'doublestorey'

[v-g-singlestorey.variantSelector]
g = 'singlestorey'
[cv12.variantSelector]
g = 'singlestorey'

[v-g-doublestorey.variantSelector]
g = 'doublestorey'
[cv11.variantSelector]
g = 'doublestorey'

[v-g-opendoublestorey.variantSelector]
g = 'opendoublestorey'
[cv24.variantSelector]
g = 'opendoublestorey'

[v-zero-slashed.variantSelector]
zero = 'slashed'
[cv13.variantSelector]
zero = 'slashed'

[v-zero-dotted.variantSelector]
zero = 'dotted'
[cv14.variantSelector]
zero = 'dotted'

[v-zero-unslashed.variantSelector]
zero = 'unslashed'
[cv15.variantSelector]
zero = 'unslashed'

[v-tilde-high.variantSelector]
asciitilde = 'high'
[cv16.variantSelector]
asciitilde = 'high'

[v-tilde-low.variantSelector]
asciitilde = 'low'
[cv17.variantSelector]
asciitilde = 'low'

[v-asterisk-high.variantSelector]
asterisk = 'high'
[cv18.variantSelector]
asterisk = 'high'

[v-asterisk-low.variantSelector]
asterisk = 'low'
[cv19.variantSelector]
asterisk = 'low'

[v-underscore-high.variantSelector]
underscore = 'high'
[cv20.variantSelector]
underscore = 'high'

[v-underscore-low.variantSelector]
underscore = 'low'
[cv21.variantSelector]
underscore = 'low'

[v-paragraph-high.variantSelector]
paragraph = 'high'
[cv22.variantSelector]
paragraph = 'high'

[v-paragraph-low.variantSelector]
paragraph = 'low'
[cv23.variantSelector]
paragraph = 'low'

[v-m-longleg.variantSelector]
m = 'longleg'
[cv25.variantSelector]
m = 'longleg'

[v-m-shortleg.variantSelector]
m = 'shortleg'
[cv26.variantSelector]
m = 'shortleg'

[v-caret-high.variantSelector]
asciicaret = 'high'
[cv29.variantSelector]
asciicaret = 'high'

[v-caret-low.variantSelector]
asciicaret = 'low'
[cv30.variantSelector]
asciicaret = 'low'

[v-at-long.variantSelector]
at = 'long'
[cv31.variantSelector]
at = 'long'

[v-at-fourfold.variantSelector]
at = 'fourfold'
[cv32.variantSelector]
at = 'fourfold'

[v-at-short.variantSelector]
at = 'short'
[cv33.variantSelector]
at = 'short'