[buildPlans.iosevka-custom]                         # <iosevka-custom> is your plan name
family = "Iosevka Custom"                           # Font menu family name
design = ["leading-1500", "v-i-hooky", "v-l-hooky"] # Customize styles
hintParams = ["-a", "sss"]                          # Optional custom parameters for ttfautohint


# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#              and "shape" properly only supports number between 100 and 900 (inclusive).
[buildPlans.iosevka-custom.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS

[buildPlans.iosevka-custom.weights.book]
shape = 450
menu  = 450  # Use 450 here to name the font's weight "Book"
css   = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu  = 700
css   = 700
# end weight section


# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-custom.slants]
upright = "normal"
italic = "italic"
oblique = "oblique"
