# Variants
[simple.v-l-hooky]
l = 'hooky'
tag = 'cv09'

[simple.v-i-hooky]
dotlessi = 'hooky'
tag = 'cv05'

[simple.v-l-zshaped]
l = 'zshaped'
tag = 'cv10'

[simple.v-i-zshaped]
dotlessi = 'zshaped'
tag = 'cv06'

[simple.v-l-serifed]
l = 'serifed'
tag = 'cv07'

[simple.v-i-serifed]
dotlessi = 'serifed'
tag = 'cv03'

[simple.v-l-italic]
l = 'italic'
tag = 'cv08'

[simple.v-i-italic]
dotlessi = 'italic'
tag = 'cv04'

[simple.v-l-tailed]
l = 'tailed'
tag = 'cv27'

[simple.v-l-hookybottom]
l = 'hookybottom'
tag = 'cv28'

[simple.v-a-singlestorey]
a = 'singlestorey'
tag = 'cv02'

[simple.v-a-doublestorey]
a = 'doublestorey'
tag = 'cv01'

[simple.v-g-singlestorey]
g = 'singlestorey'
tag = 'cv12'

[simple.v-g-doublestorey]
g = 'doublestorey'
tag = 'cv11'

[simple.v-g-opendoublestorey]
g = 'opendoublestorey'
tag = 'cv24'

[simple.v-zero-slashed]
zero = 'slashed'
tag = 'cv13'

[simple.v-zero-dotted]
zero = 'dotted'
tag = 'cv14'

[simple.v-zero-unslashed]
zero = 'unslashed'
tag = 'cv15'

[simple.v-tilde-high]
asciitilde = 'high'
tag = 'cv16'

[simple.v-tilde-low]
asciitilde = 'low'
tag = 'cv17'

[simple.v-asterisk-high]
asterisk = 'high'
tag = 'cv18'

[simple.v-asterisk-low]
asterisk = 'low'
tag = 'cv19'

[simple.v-underscore-high]
underscore = 'high'
tag = 'cv20'

[simple.v-underscore-low]
underscore = 'low'
tag = 'cv21'

[simple.v-paragraph-high]
paragraph = 'high'
tag = 'cv22'

[simple.v-paragraph-low]
paragraph = 'low'
tag = 'cv23'

[simple.v-m-longleg]
m = 'longleg'
tag = 'cv25'

[simple.v-m-shortleg]
m = 'shortleg'
tag = 'cv26'

[simple.v-caret-high]
asciicaret = 'high'
tag = 'cv29'

[simple.v-caret-low]
asciicaret = 'low'
tag = 'cv30'

[simple.v-at-long]
at = 'long'
tag = 'cv31'

[simple.v-at-fourfold]
at = 'fourfold'
tag = 'cv32'

[simple.v-at-short]
at = 'short'
tag = 'cv33'

[simple.v-eszet-traditional]
eszet = 'traditional'
tag = 'cv34'

[simple.v-eszet-sulzbacher]
eszet = 'sulzbacher'
tag = 'cv35'

[simple.v-brace-straight]
braceLeft = 'straight'
braceRight = 'straight'
tag = 'cv36'

[simple.v-brace-curly]
braceLeft = 'curly'
braceRight = 'curly'
tag = 'cv37'

[simple.v-dollar-open]
dollar = 'open'
tag = 'cv38'

[simple.v-dollar-through]
dollar = 'through'
tag = 'cv39'

[simple.v-t-standard]
t = 'standard'
tag = 'cv40'

[simple.v-t-flatend]
t = 'flatend'
tag = 'cv41'

# composites
[composite.upright]
ss01 = ['cv01', 'cv11', 'cv05', 'cv10', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Andale Mono Style
ss02 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv13', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Anonymous Pro Style
ss03 = ['cv01', 'cv11', 'cv03', 'cv07', 'cv13', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Consolas Style
ss04 = ['cv01', 'cv12', 'cv03', 'cv08', 'cv13', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31', 'cv34', 'cv36'] # Menlo Style
ss05 = ['cv01', 'cv24', 'cv03', 'cv08', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv33', 'cv34', 'cv37'] # Fira Mono Style
ss06 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv14', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Liberation Mono Style
ss07 = ['cv02', 'cv12', 'cv06', 'cv10', 'cv13', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Monaco Style
ss08 = ['cv01', 'cv11', 'cv03', 'cv07', 'cv14', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31', 'cv34', 'cv36'] # Pragmata Pro Style
ss09 = ['cv01', 'cv11', 'cv05', 'cv08', 'cv14', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv31', 'cv34', 'cv37'] # Source Code Pro Style

[composite.italic]
ss01 = ['cv01', 'cv11', 'cv05', 'cv10', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Andale Mono Style
ss02 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv13', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Anonymous Pro Style
ss03 = ['cv02', 'cv12', 'cv04', 'cv08', 'cv13', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Consolas Style
ss04 = ['cv01', 'cv12', 'cv03', 'cv08', 'cv13', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31', 'cv34', 'cv36'] # Menlo Style
ss05 = ['cv01', 'cv24', 'cv03', 'cv08', 'cv14', 'cv18', 'cv21', 'cv22', 'cv25', 'cv29', 'cv33', 'cv34', 'cv37'] # Fira Mono Style
ss06 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv14', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Liberation Mono Style
ss07 = ['cv02', 'cv12', 'cv06', 'cv10', 'cv13', 'cv18', 'cv20', 'cv22', 'cv25', 'cv29', 'cv32', 'cv34', 'cv36'] # Monaco Style
ss08 = ['cv01', 'cv12', 'cv03', 'cv07', 'cv14', 'cv19', 'cv21', 'cv22', 'cv25', 'cv29', 'cv31', 'cv34', 'cv36'] # Pragmata Pro Style
ss09 = ['cv02', 'cv12', 'cv04', 'cv08', 'cv14', 'cv19', 'cv20', 'cv22', 'cv25', 'cv29', 'cv31', 'cv34', 'cv37'] # Source Code Pro Style